template = "https://github.com/giellalt/template-lang-und"
rev_id = 338
template_sha = "f8f3c0370220064ccae6868bc90707e0583f91c2"

[replacements]
__GLOTTOLOG_ID__ = "maku1246"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
